# Generated by Django 5.2.16 on 2026-07-28 12:31

import django.db.models.deletion
import django.utils.timezone
import roadmap.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseRoadmap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('data_prevista_inicio', models.DateField(blank=True, null=True, verbose_name='início previsto')),
                ('data_prevista_conclusao', models.DateField(blank=True, null=True, verbose_name='conclusão prevista')),
                ('data_real_conclusao', models.DateField(blank=True, null=True, verbose_name='conclusão real')),
                ('status', models.CharField(choices=[('nao_iniciada', 'Não iniciada'), ('em_andamento', 'Em andamento'), ('bloqueada', 'Bloqueada'), ('concluida', 'Concluída')], default='nao_iniciada', max_length=20, verbose_name='status')),
                ('progresso', models.PositiveSmallIntegerField(default=0, verbose_name='progresso')),
                ('criterios_conclusao', models.TextField(blank=True, verbose_name='critérios de conclusão')),
                ('dependencias', models.TextField(blank=True, verbose_name='dependências')),
                ('proxima_acao', models.CharField(blank=True, max_length=240, verbose_name='próxima ação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('ordem',),
            },
        ),
        migrations.CreateModel(
            name='EntregaRoadmap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criterio_aceite', models.TextField(blank=True, verbose_name='critério de aceite')),
                ('concluida', models.BooleanField(default=False, verbose_name='concluída')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='roadmap.faseroadmap')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='FonteRoadmap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to=roadmap.models.caminho_pdf_roadmap, verbose_name='arquivo PDF')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('mime_type', models.CharField(default='application/pdf', max_length=80, verbose_name='MIME type')),
                ('tamanho', models.PositiveBigIntegerField(verbose_name='tamanho em bytes')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('quantidade_paginas', models.PositiveIntegerField(verbose_name='quantidade de páginas')),
                ('titulo_extraido', models.CharField(blank=True, max_length=240, verbose_name='título extraído')),
                ('extraido_em', models.DateTimeField(auto_now_add=True, verbose_name='extraído em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de início')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo final')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='prioridade')),
                ('progresso_manual', models.PositiveSmallIntegerField(blank=True, help_text='Deixe vazio para calcular pelas fases.', null=True, verbose_name='progresso manual')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('gerado_de_pdf', models.BooleanField(default=False, verbose_name='gerado de PDF')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('fonte_pdf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap', to='roadmap.fonteroadmap')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roadmaps', to='objetivos.objetivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='faseroadmap',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='roadmap.roadmap'),
        ),
        migrations.CreateModel(
            name='EtapaRoadmap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('concluida', models.BooleanField(default=False, verbose_name='concluída')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='roadmap.faseroadmap')),
            ],
            options={
                'ordering': ('ordem',),
                'constraints': [models.UniqueConstraint(fields=('fase', 'ordem'), name='etapa_fase_ordem_unica')],
            },
        ),
        migrations.AddIndex(
            model_name='fonteroadmap',
            index=models.Index(fields=['usuario', 'sha256'], name='fonte_roadmap_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['usuario', 'status'], name='roadmap_usuario_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['usuario', 'prazo'], name='roadmap_usuario_prazo_idx'),
        ),
        migrations.AddConstraint(
            model_name='roadmap',
            constraint=models.CheckConstraint(condition=models.Q(('progresso_manual__isnull', True), models.Q(('progresso_manual__gte', 0), ('progresso_manual__lte', 100)), _connector='OR'), name='roadmap_progresso_entre_0_100'),
        ),
        migrations.AddConstraint(
            model_name='faseroadmap',
            constraint=models.UniqueConstraint(fields=('roadmap', 'ordem'), name='fase_roadmap_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='faseroadmap',
            constraint=models.CheckConstraint(condition=models.Q(('progresso__gte', 0), ('progresso__lte', 100)), name='fase_progresso_entre_0_100'),
        ),
    ]
