# Generated by Django 5.2.16 on 2026-07-28 13:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('objetivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('problema', models.TextField(blank=True, verbose_name='problema ou oportunidade')),
                ('solucao', models.TextField(blank=True, verbose_name='solução proposta')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de início')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='data de conclusão')),
                ('status', models.CharField(choices=[('ideia', 'Ideia'), ('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='ideia', max_length=20, verbose_name='status')),
                ('progresso', models.PositiveSmallIntegerField(default=0, verbose_name='progresso')),
                ('resultado', models.TextField(blank=True, verbose_name='resultado alcançado')),
                ('aprendizados', models.TextField(blank=True, verbose_name='aprendizados')),
                ('repositorio_url', models.URLField(blank=True, verbose_name='repositório')),
                ('demonstracao_url', models.URLField(blank=True, verbose_name='demonstração')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='objetivos.objetivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='MarcoProjeto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='pendente', max_length=20, verbose_name='status')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcos', to='projetos.projeto')),
            ],
            options={
                'ordering': ('ordem', 'prazo'),
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('link', 'Link'), ('repositorio', 'Repositório'), ('documento', 'Documento'), ('captura', 'Captura de tela'), ('resultado', 'Resultado'), ('outro', 'Outro')], max_length=20, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('url', models.URLField(blank=True, verbose_name='link')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('validada', models.BooleanField(default=False, verbose_name='evidência validada')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_projeto', to='biblioteca.materialpdf')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='projetos.projeto')),
            ],
            options={
                'ordering': ('-data', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TarefaProjeto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20, verbose_name='status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='prioridade')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos.projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('ordem', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem'), ('framework', 'Framework'), ('nuvem', 'Nuvem'), ('banco', 'Banco de dados'), ('infra', 'Infraestrutura'), ('ferramenta', 'Ferramenta'), ('outro', 'Outro')], default='ferramenta', max_length=20, verbose_name='categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='ProjetoTecnologia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologias_vinculadas', to='projetos.projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_vinculados', to='projetos.tecnologia')),
            ],
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['usuario', 'status'], name='projeto_usuario_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['usuario', 'prazo'], name='projeto_usuario_prazo_idx'),
        ),
        migrations.AddConstraint(
            model_name='projeto',
            constraint=models.CheckConstraint(condition=models.Q(('progresso__gte', 0), ('progresso__lte', 100)), name='projeto_progresso_0_100'),
        ),
        migrations.AddConstraint(
            model_name='marcoprojeto',
            constraint=models.UniqueConstraint(fields=('projeto', 'ordem'), name='marco_projeto_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='tarefaprojeto',
            constraint=models.UniqueConstraint(fields=('projeto', 'ordem'), name='tarefa_projeto_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='tecnologia',
            constraint=models.UniqueConstraint(fields=('usuario', 'nome'), name='tecnologia_usuario_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='projetotecnologia',
            constraint=models.UniqueConstraint(fields=('projeto', 'tecnologia'), name='projeto_tecnologia_unica'),
        ),
    ]
