# Generated by Django 5.2.16 on 2026-07-28 12:56

import biblioteca.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPDF',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('arquivo', models.FileField(upload_to=biblioteca.models.caminho_pdf_aula, verbose_name='arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('tamanho', models.PositiveBigIntegerField(verbose_name='tamanho em bytes')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('quantidade_paginas', models.PositiveIntegerField(verbose_name='quantidade de páginas')),
                ('principal', models.BooleanField(default=False, verbose_name='PDF principal da aula')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais_pdf', to='estudos.aula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['usuario', 'aula'], name='material_usuario_aula_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('aula',), name='um_pdf_principal_por_aula')],
            },
        ),
    ]
