# Generated by Django 5.2.16 on 2026-07-28 12:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('categoria', models.CharField(choices=[('profissional', 'Profissional'), ('academico', 'Acadêmico'), ('pessoal', 'Pessoal'), ('financeiro', 'Financeiro'), ('saude', 'Saúde'), ('comunicacao', 'Comunicação'), ('outro', 'Outro')], default='profissional', max_length=20, verbose_name='categoria')),
                ('motivo', models.TextField(blank=True, verbose_name='por que este objetivo importa?')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de início')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('atrasado', 'Atrasado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=20, verbose_name='status')),
                ('progresso', models.PositiveSmallIntegerField(default=0, verbose_name='progresso')),
                ('resultado_esperado', models.TextField(blank=True, verbose_name='resultado esperado')),
                ('evidencia_esperada', models.TextField(blank=True, verbose_name='evidência esperada')),
                ('proxima_acao', models.CharField(blank=True, max_length=240, verbose_name='próxima ação')),
                ('obstaculos', models.TextField(blank=True, verbose_name='obstáculos')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('data_conclusao', models.DateField(blank=True, editable=False, null=True, verbose_name='data de conclusão')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='objetivos.tag', verbose_name='tags')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='HistoricoObjetivo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('criacao', 'Criação'), ('alteracao', 'Alteração'), ('arquivamento', 'Arquivamento'), ('restauracao', 'Restauração')], max_length=20, verbose_name='tipo')),
                ('campo', models.CharField(blank=True, max_length=50, verbose_name='campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='valor anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='valor novo')),
                ('descricao', models.CharField(max_length=240, verbose_name='descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_objetivos', to=settings.AUTH_USER_MODEL)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='objetivos.objetivo')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['objetivo', 'created_at'], name='historico_objetivo_data_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('usuario', 'slug'), name='objetivos_tag_usuario_slug_unico'),
        ),
        migrations.AddIndex(
            model_name='objetivo',
            index=models.Index(fields=['usuario', 'status'], name='objetivo_usuario_status_idx'),
        ),
        migrations.AddIndex(
            model_name='objetivo',
            index=models.Index(fields=['usuario', 'prazo'], name='objetivo_usuario_prazo_idx'),
        ),
        migrations.AddIndex(
            model_name='objetivo',
            index=models.Index(fields=['usuario', 'status', 'prazo'], name='objetivo_status_prazo_idx'),
        ),
        migrations.AddIndex(
            model_name='objetivo',
            index=models.Index(fields=['usuario', 'updated_at'], name='objetivo_usuario_atual_idx'),
        ),
        migrations.AddConstraint(
            model_name='objetivo',
            constraint=models.CheckConstraint(condition=models.Q(('progresso__gte', 0), ('progresso__lte', 100)), name='objetivo_progresso_entre_0_100'),
        ),
    ]
