# Generated by Django 5.2.16 on 2026-07-28 13:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('estudos', '0001_initial'),
        ('objetivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=180, verbose_name='certificação')),
                ('instituicao', models.CharField(max_length=140, verbose_name='instituição')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('preparando', 'Em preparação'), ('agendada', 'Prova agendada'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='prioridade')),
                ('progresso', models.PositiveSmallIntegerField(default=0, verbose_name='progresso da preparação')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='início da preparação')),
                ('data_prova', models.DateField(blank=True, null=True, verbose_name='data da prova')),
                ('data_resultado', models.DateField(blank=True, null=True, verbose_name='data do resultado')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='validade até')),
                ('custo_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='custo previsto')),
                ('custo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='custo real')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='nota obtida')),
                ('url_oficial', models.URLField(blank=True, verbose_name='página oficial')),
                ('url_agendamento', models.URLField(blank=True, verbose_name='página de agendamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivada em')),
                ('certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificacoes', to='biblioteca.materialpdf')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificacoes', to='objetivos.objetivo')),
                ('trilha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificacoes', to='estudos.trilha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('data_prova', '-prioridade', 'nome'),
                'indexes': [models.Index(fields=['usuario', 'status'], name='cert_usuario_status_idx'), models.Index(fields=['usuario', 'data_prova'], name='cert_usuario_prova_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('progresso__gte', 0), ('progresso__lte', 100)), name='certificacao_progresso_0_100')],
            },
        ),
    ]
