# Generated by Django 5.2.16 on 2026-07-28 13:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('categoria', models.CharField(choices=[('tecnica', 'Técnica'), ('comportamental', 'Comportamental'), ('negocio', 'Negócio'), ('idioma', 'Idioma'), ('lideranca', 'Liderança'), ('outra', 'Outra')], max_length=20, verbose_name='categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('nivel_desejado', models.PositiveSmallIntegerField(default=3, verbose_name='nível desejado')),
                ('criterios', models.TextField(blank=True, help_text='Descreva o que precisa demonstrar para avançar de nível.', verbose_name='critérios de evolução')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('arquivado_em', models.DateTimeField(blank=True, null=True, verbose_name='arquivada em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('categoria', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoCompetencia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.PositiveSmallIntegerField(verbose_name='nível demonstrado')),
                ('justificativa', models.TextField(verbose_name='justificativa')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='data da avaliação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='competencias.competencia')),
            ],
            options={
                'ordering': ('-data', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EvidenciaCompetencia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_evidencia', to='competencias.avaliacaocompetencia')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_competencia', to='projetos.evidencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='avaliacaocompetencia',
            name='evidencias',
            field=models.ManyToManyField(related_name='avaliacoes_competencia', through='competencias.EvidenciaCompetencia', to='projetos.evidencia'),
        ),
        migrations.AddIndex(
            model_name='competencia',
            index=models.Index(fields=['usuario', 'categoria'], name='competencia_usuario_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='competencia',
            constraint=models.UniqueConstraint(fields=('usuario', 'nome'), name='competencia_usuario_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='competencia',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_desejado__gte', 1), ('nivel_desejado__lte', 5)), name='competencia_nivel_desejado_1_5'),
        ),
        migrations.AddConstraint(
            model_name='evidenciacompetencia',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'evidencia'), name='avaliacao_evidencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='avaliacaocompetencia',
            constraint=models.CheckConstraint(condition=models.Q(('nivel__gte', 1), ('nivel__lte', 5)), name='avaliacao_nivel_1_5'),
        ),
    ]
