# Generated by Django 5.2.16 on 2026-07-28 12:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('instituicao', models.CharField(blank=True, max_length=180, verbose_name='instituição')),
                ('tipo', models.CharField(choices=[('graduacao', 'Graduação'), ('pos', 'Pós-graduação'), ('livre', 'Curso livre'), ('certificacao', 'Certificação'), ('corporativo', 'Treinamento'), ('outro', 'Outro')], max_length=20, verbose_name='tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('data_prevista_conclusao', models.DateField(blank=True, null=True, verbose_name='conclusão prevista')),
                ('data_real_conclusao', models.DateField(blank=True, null=True, verbose_name='conclusão real')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20, verbose_name='status')),
                ('carga_horaria', models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='carga horária')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('numero', models.PositiveSmallIntegerField(default=1, verbose_name='número')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='data de conclusão')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='estudos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('codigo', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('professor', models.CharField(blank=True, max_length=180, verbose_name='professor')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('carga_horaria', models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='carga horária')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20, verbose_name='status')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota')),
                ('frequencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='frequência (%)')),
                ('progresso', models.PositiveSmallIntegerField(default=0, verbose_name='progresso')),
                ('ementa', models.TextField(blank=True, verbose_name='ementa')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='estudos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='estudos.periodo')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('categoria', models.CharField(choices=[('faculdade', 'Faculdade'), ('pos', 'Pós-graduação'), ('azure', 'Azure'), ('windows', 'Windows Server'), ('redes', 'Redes'), ('seguranca', 'Segurança'), ('powershell', 'PowerShell'), ('python', 'Python'), ('devops', 'DevOps'), ('outro', 'Outro')], max_length=20, verbose_name='categoria')),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20, verbose_name='nível')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='prioridade')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de início')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20, verbose_name='status')),
                ('progresso', models.PositiveSmallIntegerField(default=0, verbose_name='progresso')),
                ('carga_horaria_prevista', models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='carga horária prevista')),
                ('carga_horaria_realizada', models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='carga horária realizada')),
                ('prerequisitos', models.TextField(blank=True, verbose_name='pré-requisitos')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trilhas', to='objetivos.objetivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='trilhas',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='estudos.trilha'),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('numero', models.PositiveSmallIntegerField(default=1, verbose_name='número da aula')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('professor', models.CharField(blank=True, max_length=180, verbose_name='professor')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejado', max_length=20, verbose_name='status')),
                ('duracao_prevista', models.PositiveIntegerField(default=0, verbose_name='duração prevista (min)')),
                ('duracao_estudada', models.PositiveIntegerField(default=0, verbose_name='duração estudada (min)')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil')], default='media', max_length=10, verbose_name='dificuldade')),
                ('resumo', models.TextField(blank=True, verbose_name='resumo')),
                ('duvidas', models.TextField(blank=True, verbose_name='dúvidas')),
                ('aplicacao_pratica', models.TextField(blank=True, verbose_name='aplicação prática')),
                ('proxima_revisao', models.DateField(blank=True, null=True, verbose_name='próxima revisão')),
                ('concluida', models.BooleanField(default=False, verbose_name='concluída')),
                ('favorita', models.BooleanField(default=False, verbose_name='favorita')),
                ('tags', models.CharField(blank=True, max_length=240, verbose_name='tags')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='estudos.disciplina')),
            ],
            options={
                'ordering': ('-data', '-numero'),
                'indexes': [models.Index(fields=['usuario', 'disciplina', 'data'], name='aula_usuario_disc_data_idx'), models.Index(fields=['usuario', 'concluida', 'data'], name='aula_usuario_concl_data_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='periodo',
            constraint=models.UniqueConstraint(fields=('curso', 'numero'), name='periodo_curso_numero_unico'),
        ),
        migrations.AddIndex(
            model_name='disciplina',
            index=models.Index(fields=['usuario', 'status'], name='disciplina_usuario_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='disciplina',
            constraint=models.CheckConstraint(condition=models.Q(('progresso__gte', 0), ('progresso__lte', 100)), name='disciplina_progresso_0_100'),
        ),
        migrations.AddIndex(
            model_name='trilha',
            index=models.Index(fields=['usuario', 'status'], name='trilha_usuario_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='trilha',
            constraint=models.CheckConstraint(condition=models.Q(('progresso__gte', 0), ('progresso__lte', 100)), name='trilha_progresso_0_100'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['usuario', 'status'], name='curso_usuario_status_idx'),
        ),
    ]
