# Generated by Django 5.2.16 on 2026-07-28 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iniciada_em', models.DateTimeField(verbose_name='iniciada em')),
                ('encerrada_em', models.DateTimeField(verbose_name='encerrada em')),
                ('duracao_segundos', models.PositiveIntegerField(verbose_name='duração (segundos)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-encerrada_em',),
                'indexes': [models.Index(fields=['usuario', 'iniciada_em'], name='sessao_usuario_inicio_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duracao_segundos__gt', 0)), name='sessao_duracao_positiva'), models.CheckConstraint(condition=models.Q(('encerrada_em__gte', models.F('iniciada_em'))), name='sessao_fim_apos_inicio')],
            },
        ),
    ]
