# Generated by Django 5.2.16 on 2026-07-28 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencias', '0001_initial'),
        ('objetivos', '0001_initial'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisaoPeriodica',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('tipo', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=15, verbose_name='tipo')),
                ('periodo_inicio', models.DateField(verbose_name='início do período')),
                ('periodo_fim', models.DateField(verbose_name='fim do período')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('concluida', 'Concluída')], default='rascunho', max_length=15, verbose_name='status')),
                ('nota_periodo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nota do período')),
                ('conquistas', models.TextField(blank=True, verbose_name='principais conquistas')),
                ('dificuldades', models.TextField(blank=True, verbose_name='dificuldades e bloqueios')),
                ('aprendizados', models.TextField(blank=True, verbose_name='aprendizados')),
                ('ajustes', models.TextField(blank=True, verbose_name='o que ajustar no próximo ciclo')),
                ('conclusao', models.TextField(blank=True, verbose_name='conclusão')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-periodo_fim', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AcaoRevisao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=240, verbose_name='ação')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='status')),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acoes_revisao', to='competencias.competencia')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acoes_revisao', to='objetivos.objetivo')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acoes_revisao', to='projetos.projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
                ('revisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='revisoes.revisaoperiodica')),
            ],
            options={
                'ordering': ('status', 'prazo', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='revisaoperiodica',
            index=models.Index(fields=['usuario', 'status'], name='revisao_usuario_status_idx'),
        ),
        migrations.AddIndex(
            model_name='revisaoperiodica',
            index=models.Index(fields=['usuario', 'periodo_fim'], name='revisao_usuario_fim_idx'),
        ),
        migrations.AddConstraint(
            model_name='revisaoperiodica',
            constraint=models.CheckConstraint(condition=models.Q(('nota_periodo__isnull', True), models.Q(('nota_periodo__gte', 1), ('nota_periodo__lte', 5)), _connector='OR'), name='revisao_nota_1_5'),
        ),
        migrations.AddIndex(
            model_name='acaorevisao',
            index=models.Index(fields=['usuario', 'status', 'prazo'], name='acao_revisao_prazo_idx'),
        ),
    ]
