# Generated by Django 5.2.16 on 2026-07-28 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('conteudo_html', models.TextField(blank=True, verbose_name='conteúdo')),
                ('conteudo_texto', models.TextField(blank=True, verbose_name='texto pesquisável')),
                ('tipo', models.CharField(choices=[('geral', 'Anotação geral'), ('resumo', 'Resumo'), ('duvida', 'Dúvida'), ('conceito', 'Conceito importante'), ('exercicio', 'Exercício'), ('pratica', 'Aplicação prática'), ('ideia', 'Ideia de projeto'), ('revisao', 'Revisão'), ('codigo', 'Bloco de código')], default='geral', max_length=20, verbose_name='tipo')),
                ('pagina_pdf', models.PositiveIntegerField(blank=True, null=True, verbose_name='página do PDF')),
                ('trecho_referencia', models.TextField(blank=True, verbose_name='trecho de referência')),
                ('favorita', models.BooleanField(default=False, verbose_name='favorita')),
                ('tags', models.CharField(blank=True, max_length=240, verbose_name='tags')),
                ('versao_atual', models.PositiveIntegerField(default=1, verbose_name='versão atual')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anotacoes', to='estudos.aula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VersaoAnotacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(verbose_name='número')),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('conteudo_html', models.TextField(verbose_name='conteúdo')),
                ('conteudo_texto', models.TextField(blank=True, verbose_name='texto')),
                ('anotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='anotacoes.anotacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-numero',),
            },
        ),
        migrations.AddIndex(
            model_name='anotacao',
            index=models.Index(fields=['usuario', 'aula', 'updated_at'], name='anotacao_aula_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='versaoanotacao',
            constraint=models.UniqueConstraint(fields=('anotacao', 'numero'), name='versao_anotacao_numero_unico'),
        ),
    ]
